### ISSUE TITLE
i have an error

### ISSUE THREAD

**Issue by 108527307** [sangwoo3/summarization-dpp-capsnet#1]
Can not do batch_dot on inputs with shapes (None, 12, 12, 30) and (None, 12, None, 30) with axes=[2, 3]. x.shape[2] != y.shape[3] (12 != 30).
 this error happened when the program ran in the 72 lines in model.py file.

**Comment by sangwoo3** [comment]
Hi,
I guess you have a problem in line 69 of the model.py file. The shapes of each variable look as follows.
u_hat = [B, n_cap, in_cap, d_cap]
b = [B, n_cap, in_cap]
c = [B, n_cap, in_cap]
outputs = batch_dot (c,u_hat, [2,2]) = [B, n_cap, d_cap]
batch_dot(outputs, u_hat, [2,3]) = [B, n_cap, in_cap]
I am not sure why you have the shape of (None, 12, None, 30) with the input shape of (None, 12, 12, 30) but it should be (None, 12, 30).

**Comment by sangwoo3** [comment]
Please let me know if you have a problem.
I close the issue.
